export const COMMUNITY_POST_TAGS = [
  'backtoschool',
  'coronavirus',
  'mylife',
  'myschool',
  'news',
  'hobbies',
  'sport',
  'lookingforhelp',
  'debates',
  'environment',
  'changemakers',
  'holidays',
  'technologies',
  'photochallenge',
  'happiness',
]
