export const SOCIAL_LINKS = {
  twitter: 'https://twitter.com/idialogue_lab',
  facebook: 'https://www.facebook.com/idialoguelab',
  instagram: 'https://www.instagram.com/idialogue_global',
}

export const INTERESTS = [
  'Art',
  'Basketball',
  'Blogging',
  'Books',
  'Cars',
  'Coding',
  'Cooking',
  'Cycling',
  'Dance',
  'Design',
  'Football',
  'Movies',
  'Music',
  'Origami',
  'Outdoor activities',
  'Painting',
  'Photography',
  'Reading',
  'Robotics',
  'Skiing',
  'Sports',
  'Swimming',
  'Technology',
  'Traveling',
  'Tv',
  'Video games',
  'Writing',
  'Yoga',
]
