export const DISCUSSIONS_TAGS = [
  'Collaborative Projects',
  'Culture & Traditions',
  'Discussions',
  'Esl',
  'Professional Development',
  'Social & Emotional Learning',
  'Social Studies',
  'Technology',
  'Virtual Tours',
  'Collaboration',
  'Penpals',
  'Curriculum',
  'Classroom Management & Strategies',
  'Pedagogy & Best Practices',
  'Teacher Support & Advice',
  'Humor',
  'Helpful Materials & Resources',
]
